name: ci-cd

on:
  push:
    branches: [ master ]
  workflow_dispatch:

env:
  IMAGE_NAME: ${{ secrets.DOCKER_USERNAME }}/lna-gateway
  GH_PKG_TOKEN: ${{ secrets.GH_PKG_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Maven settings.xml
        run: |
          mkdir -p ~/.m2
          echo "<settings xmlns=\"http://maven.apache.org/SETTINGS/1.0.0\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xsi:schemaLocation=\"http://maven.apache.org/SETTINGS/1.0.0 https://maven.apache.org/xsd/settings-1.0.0.xsd\">
            <servers>
              <server>
                <id>github</id>
                <username>nullnonamenull</username>
                <password>${{ secrets.GH_PKG_TOKEN }}</password>
              </server>
            </servers>
            <mirrors>
              <mirror>
                <id>github</id>
                <name>GitHub Maven Repository</name>
                <url>https://maven.pkg.github.com/nullnonamenull</url>
                <mirrorOf>*</mirrorOf>
              </mirror>
            </mirrors>
          </settings>" > ~/.m2/settings.xml

      - name: Debug - Validate GitHub Package Access
        run: |
          curl -v -u nullnonamenull:${{ secrets.GH_PKG_TOKEN }} \
          https://maven.pkg.github.com/nullnonamenull/lna-processor-dto/com/noname/lna-processor-dto/maven-metadata.xml

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: maven

      - name: Build JAR with debug
        run: mvn -B -X -f lna-gateway/pom.xml clean package

      - uses: docker/setup-buildx-action@v3
        if: success()

      - uses: docker/login-action@v3
        if: success()
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - uses: docker/build-push-action@v6
        if: success()
        with:
          context: ./lna-gateway
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:latest
            ${{ env.IMAGE_NAME }}:${{ github.sha }}