name: ci-cd

on:
  push:
    branches: [ master ]
  pull_request:
  workflow_dispatch:

permissions:
  contents: read
  packages: write

env:
  DOCKER_IMAGE: ${{ secrets.DOCKER_USERNAME }}/lna-gateway

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Temurin 21 and Maven auth
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven
          server-id: github
          server-username: GH_PKG_USER
          server-password: GH_PKG_TOKEN
        env:
          GH_PKG_USER: ${{ github.actor }}
          GH_PKG_TOKEN: ${{ secrets.GH_PKG_TOKEN }}

      # ── 3. compile & test ─────────────────────────────
      - name: Build with Maven
        run: mvn -B -f lna-gateway/pom.xml clean package
        env:
          GH_PKG_TOKEN: ${{ secrets.GH_PKG_TOKEN }}

      # ── 4. build & push Docker image ─────────────────
      - uses: docker/setup-buildx-action@v3

      - name: Docker login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & push image
        uses: docker/build-push-action@v6
        with:
          context: ./lna-gateway
          file: ./Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ env.DOCKER_IMAGE }}:latest
            ${{ env.DOCKER_IMAGE }}:${{ github.sha }}