name: ci-cd
on:
  push:
    branches: [ master ]
  workflow_dispatch:

permissions:
  contents: read
  packages: read

env:
  IMAGE_NAME: ${{ secrets.DOCKER_USERNAME }}/lna-gateway

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: maven
          server-id: github
          server-username: ${{ github.actor }}
          server-password: ${{ secrets.GH_PKG_TOKEN }}

      # ---------- DEBUG START ----------
      - name: settings.xml (masked)
        run: |
          echo "::group::settings.xml"
          sed 's/<password>.*<\/password>/<password>***<\/password>/' ~/.m2/settings.xml
          echo "::endgroup::"

      - name: curl test lna-session-dto 0.0.8
        run: |
          curl -s -o /dev/null -w "lna-session-dto -> %{http_code}\n" \
               -u "${{ github.actor }}:${{ secrets.GH_PKG_TOKEN }}" \
               https://maven.pkg.github.com/nullnonamenull/lna-session-dto/com/noname/lna-session-dto/0.0.8/lna-session-dto-0.0.8.pom

      - name: curl test lna-processor-dto 0.0.5
        run: |
          curl -s -o /dev/null -w "lna-processor-dto -> %{http_code}\n" \
               -u "${{ github.actor }}:${{ secrets.GH_PKG_TOKEN }}" \
               https://maven.pkg.github.com/nullnonamenull/lna-processor-dto/com/noname/lna-processor-dto/0.0.5/lna-processor-dto-0.0.5.pom
      # ---------- DEBUG END ------------

      - name: Build & test
        run: mvn -B -f lna-gateway/pom.xml verify

      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - uses: docker/build-push-action@v6
        with:
          context: ./lna-gateway
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:latest
            ${{ env.IMAGE_NAME }}:${{ github.sha }}