name: deploy

on:
  push:
    branches: [ master ]

env:
  DOCKER_IMAGE: ${{ secrets.DOCKER_USERNAME }}/lna-gateway

jobs:
  maven-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven
      - name: Build with Maven
        run: mvn -B -f lna-gateway/pom.xml clean package

      - name: Upload JAR
        uses: actions/upload-artifact@v4
        with:
          name: jar
          path: lna-gateway/target/*.jar

  docker-build:
    runs-on: ubuntu-latest
    needs: maven-build
    steps:
      - uses: actions/checkout@v4
      - name: Download JAR
        uses: actions/download-artifact@v4
        with:
          name: jar
          path: lna-gateway/target
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build & push image
        uses: docker/build-push-action@v6
        with:
          context: ./lna-gateway
          file: ./Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ env.DOCKER_IMAGE }}:latest
            ${{ env.DOCKER_IMAGE }}:${{ github.sha }}