name: ci-cd
on:
  push:
    branches: [ master ]
  workflow_dispatch:

permissions:
  contents: read
  packages: read

env:
  IMAGE_NAME: ${{ secrets.DOCKER_USERNAME }}/lna-gateway
  GH_PKG_USER: ${{ secrets.GH_PKG_USER }}
  GH_PKG_TOKEN: ${{ secrets.GH_PKG_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: maven
          server-id: github
          server-username: GH_PKG_USER
          server-password: GH_PKG_TOKEN

      - name: Build & test
        run: mvn -B -f lna-gateway/pom.xml verify

      # Docker
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - uses: docker/build-push-action@v6
        with:
          context: ./lna-gateway
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:latest
            ${{ env.IMAGE_NAME }}:${{ github.sha }}